df=read.csv('HistoricalQuotes.csv')
#df_1=read.csv('HistoricalQuotes_1.csv')
df_2=read.csv('HistoricalQuotes (2).csv')
tse=ts(df$close)
library(ggplot2)
ggplot(data=df, aes(as.Date(df$date,'%m/%d/%Y'),tse))+geom_line()+geom_point()+xlab('date')+ylab('price') 
BoxCox.ar(tse)
BoxCox.ar(tse^-1)
warning()
plot(ts(df$close),type='o',ylab='closing price',main='fb stock price')
tse=ts(df$close)
#tse_1=ts(df_1$close)
tse_2=ts(df_2$close)
library(MASS)
library(TSA)
library(forecast)
acf(tse)
pacf(tse)
#it is not stationary
adf.test(diff(tse^-1,1))
#auto.arima(tse)
plot(armasubsets(y=diff(tse^-1,1),nar=7,nma=7,y.name='test', ar.method='ols'))
## We will take AR(1,0,4) , AR(2,0,4),AR(3,0,4),AR(1,0,5)
acf(diff(tse^-1,1),lag=100)
pacf(diff(tse^-1,1))
f1<-arima(tse^-1,order=c(0,1,3))
f2<-arima(tse^-1,order=c(0,1,7))
f3<-arima(tse^-1,order=c(2,1,7))
f4<-arima(tse^-1,order=c(5,1,7))
#auto.arima(diff(tse^-1),2)
AIC(f1,f2,f3,f4)
tsdiag(f2)
library(astsa)
sarima(tse^-1,p=0,d=1,q=3)
sarima(tse^-1,p=0,d=1,q=7)
sarima(tse^-1,p=2,d=1,q=7)
sarima.(tse^-1,p=5,d=1,q=7)
#sarima(diff(tse^-1,2),p=3,d=0,q=4)
#sarima(diff(tse^-1,2),p=4,d=0,q=7)

plot(rstandard(f5),ylab='Standardized residuals',type='l')
abline(h=0)
qqnorm(residuals(f5))
qqline(residuals(f5))
shapiro.test(rstandard(f4))
acf(rstandard(arima(tse^-1,order=c(3,2,4))))
#acf(rstandard(arima(tse^-1,order=c(4,2,7))))
Box.test(resid(f5),type="Ljung",lag=20,fitdf=1) ## residuals are independent
#tsdiag(arima(diff(tse^-1,2),order=c(4,0,7)))

##Forecasting###a<-sarima.for((diff(tse,2))^2,n.ahead = 10,2,0,5)
a<-sarima.for(tse^-1,n.ahead = 10,5,1,7)
b<-a$pred[1:10]
b
#ts.plot(c)
c<-b^(-1)
#c<-as.numeric(diff(tse^-1,2))

d<-c(tse,c)
#par(mfrow(c(1,2))) 
ts.plot(d,type='o')
ts.plot(tse,type='o')
ts.plot(tse_2,type='o',ylim=c(160,180))
ts.plot(c[1:7],type='o',ylim=c(160,180),main="Predicted and Actual Value",ylab="Share Price")
points(tse_2,type = "o", col = 2, lty = 2)
legend("topleft", legend = c("Predicted","Actual"), col = 1:2, lty = 1)

